"""
CLAUDE.md Compliance Integration Tool

Bu tool, compliance checker'ı development workflow'una entegre eder ve
Git hooks, pre-commit checks ve CI/CD pipeline entegrasyonu sağlar.
"""

import os
import json
import subprocess
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime

from claude_compliance_checker import ClaudeComplianceChecker, ComplianceViolation

# Logging setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ComplianceIntegrationTool:
    """
    Compliance checker'ı development workflow'una entegre eden tool
    """
    
    def __init__(self, project_root: str = None):
        """
        Integration tool'unu başlat
        
        Args:
            project_root: Proje kök dizini
        """
        self.project_root = project_root or "/home/ahmet/MetisAgent/MetisAgent2"
        self.compliance_checker = ClaudeComplianceChecker(self.project_root)
        self.hooks_dir = os.path.join(self.project_root, ".git", "hooks")
        self.compliance_dir = os.path.join(self.project_root, ".compliance")
        
        # Compliance dizinini oluştur
        os.makedirs(self.compliance_dir, exist_ok=True)
    
    def setup_git_hooks(self) -> bool:
        """
        Git hooks kurulumu yapar
        
        Returns:
            Kurulum başarılı mı
        """
        try:
            # .git klasörü var mı kontrol et
            if not os.path.exists(self.hooks_dir):
                logger.warning("Git repository bulunamadı, hooks kurulamadı")
                return False
            
            # Pre-commit hook oluştur
            pre_commit_hook = self._create_pre_commit_hook()
            pre_commit_path = os.path.join(self.hooks_dir, "pre-commit")
            
            with open(pre_commit_path, 'w') as f:
                f.write(pre_commit_hook)
            
            # Executable yap
            os.chmod(pre_commit_path, 0o755)
            
            # Pre-push hook oluştur
            pre_push_hook = self._create_pre_push_hook()
            pre_push_path = os.path.join(self.hooks_dir, "pre-push")
            
            with open(pre_push_path, 'w') as f:
                f.write(pre_push_hook)
            
            # Executable yap
            os.chmod(pre_push_path, 0o755)
            
            logger.info("Git hooks başarıyla kuruldu")
            return True
            
        except Exception as e:
            logger.error(f"Git hooks kurulumu hatası: {e}")
            return False
    
    def _create_pre_commit_hook(self) -> str:
        """
        Pre-commit hook script'ini oluşturur
        """
        return f"""#!/bin/bash
# CLAUDE.md Compliance Pre-commit Hook
# Auto-generated by ComplianceIntegrationTool

echo "🔍 CLAUDE.md compliance kontrolü yapılıyor..."

# Python path setup
export PYTHONPATH="{self.project_root}:$PYTHONPATH"

# Compliance checker çalıştır
cd "{self.project_root}"
python -c "
import sys
sys.path.insert(0, '{self.project_root}/tools/internal')
from compliance_integration_tool import ComplianceIntegrationTool

tool = ComplianceIntegrationTool()
success = tool.check_staged_files_compliance()

if not success:
    print('❌ Compliance kontrolü başarısız!')
    print('💡 Compliance raporu: .compliance/last_check_report.json')
    sys.exit(1)
else:
    print('✅ Compliance kontrolü başarılı!')
"

# Exit code'a göre commit'e izin ver veya reddet
if [ $? -ne 0 ]; then
    echo "❌ Commit rejected due to compliance violations"
    exit 1
fi

echo "✅ Commit approved"
exit 0
"""

    def _create_pre_push_hook(self) -> str:
        """
        Pre-push hook script'ini oluşturur
        """
        return f"""#!/bin/bash
# CLAUDE.md Compliance Pre-push Hook
# Auto-generated by ComplianceIntegrationTool

echo "🔍 Push öncesi CLAUDE.md compliance kontrolü..."

# Python path setup
export PYTHONPATH="{self.project_root}:$PYTHONPATH"

# Full project compliance check
cd "{self.project_root}"
python -c "
import sys
sys.path.insert(0, '{self.project_root}/tools/internal')
from compliance_integration_tool import ComplianceIntegrationTool

tool = ComplianceIntegrationTool()
success = tool.full_project_compliance_check()

if not success:
    print('❌ Full project compliance kontrolü başarısız!')
    print('💡 Detaylı rapor: .compliance/pre_push_report.json')
    sys.exit(1)
else:
    print('✅ Full project compliance kontrolü başarılı!')
"

# Exit code'a göre push'a izin ver veya reddet
if [ $? -ne 0 ]; then
    echo "❌ Push rejected due to compliance violations"
    exit 1
fi

echo "✅ Push approved"
exit 0
"""

    def check_staged_files_compliance(self) -> bool:
        """
        Git'te staged olan dosyaların compliance kontrolü
        
        Returns:
            Tüm staged dosyalar compliant mi
        """
        try:
            # Staged Python dosyalarını al
            result = subprocess.run(
                ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
                capture_output=True, text=True, cwd=self.project_root
            )
            
            if result.returncode != 0:
                logger.error("Git staged files alınamadı")
                return False
            
            staged_files = [
                f for f in result.stdout.strip().split('\n') 
                if f.endswith('.py') and f.strip()
            ]
            
            if not staged_files:
                logger.info("Staged Python dosyası bulunamadı")
                return True
            
            # Staged dosyaları kontrol et
            all_violations = []
            
            for file_path in staged_files:
                full_path = os.path.join(self.project_root, file_path)
                if os.path.exists(full_path):
                    violations = self.compliance_checker.check_file_compliance(full_path)
                    all_violations.extend(violations)
            
            # Sonuçları kaydet
            report = {
                "timestamp": datetime.now().isoformat(),
                "check_type": "staged_files",
                "files_checked": staged_files,
                "total_violations": len(all_violations),
                "violations": [
                    self.compliance_checker._make_serializable(v) 
                    for v in all_violations
                ]
            }
            
            report_path = os.path.join(self.compliance_dir, "last_check_report.json")
            with open(report_path, 'w') as f:
                json.dump(report, f, indent=2)
            
            # Critical violations var mı kontrol et
            critical_violations = [v for v in all_violations if v.severity == "critical"]
            
            if critical_violations:
                logger.error(f"🚨 {len(critical_violations)} critical compliance violation bulundu!")
                for violation in critical_violations:
                    logger.error(f"   {violation.file_path}:{violation.line_number} - {violation.rule_name}")
                return False
            
            # High violations çok fazla mı
            high_violations = [v for v in all_violations if v.severity == "high"]
            if len(high_violations) > 3:  # Threshold
                logger.error(f"🚨 Çok fazla high-severity violation: {len(high_violations)}")
                return False
            
            if all_violations:
                logger.warning(f"⚠️ {len(all_violations)} compliance violation bulundu, ancak critical değil")
            
            return True
            
        except Exception as e:
            logger.error(f"Staged files compliance check hatası: {e}")
            return False
    
    def full_project_compliance_check(self) -> bool:
        """
        Tüm projenin compliance kontrolü
        
        Returns:
            Proje compliant mi
        """
        try:
            report = self.compliance_checker.check_project_compliance()
            
            # Raporu kaydet
            report_path = os.path.join(self.compliance_dir, "pre_push_report.json")
            self.compliance_checker.export_report(report, report_path)
            
            # Compliance score threshold
            compliance_score = report["summary"]["compliance_score"]
            min_score = 85.0  # Minimum kabul edilebilir score
            
            # Critical violations kontrolü
            critical_count = report["summary"]["critical_violations"]
            
            if critical_count > 0:
                logger.error(f"🚨 {critical_count} critical violation bulundu!")
                return False
            
            if compliance_score < min_score:
                logger.error(f"🚨 Compliance score çok düşük: {compliance_score}% (min: {min_score}%)")
                return False
            
            logger.info(f"✅ Compliance score: {compliance_score}%")
            return True
            
        except Exception as e:
            logger.error(f"Full project compliance check hatası: {e}")
            return False
    
    def generate_compliance_dashboard(self) -> str:
        """
        Web tabanlı compliance dashboard oluşturur
        
        Returns:
            Dashboard HTML path
        """
        try:
            # Son compliance raporunu al
            report = self.compliance_checker.check_project_compliance()
            
            # HTML dashboard oluştur
            html_content = self._create_dashboard_html(report)
            
            dashboard_path = os.path.join(self.compliance_dir, "compliance_dashboard.html")
            with open(dashboard_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            logger.info(f"Compliance dashboard oluşturuldu: {dashboard_path}")
            return dashboard_path
            
        except Exception as e:
            logger.error(f"Dashboard oluşturma hatası: {e}")
            return ""
    
    def _create_dashboard_html(self, report: Dict[str, Any]) -> str:
        """
        Compliance dashboard HTML'ini oluşturur
        """
        summary = report["summary"]
        
        # Violation stats
        severity_stats = ""
        for severity in ["critical", "high", "medium", "low"]:
            count = summary[f"{severity}_violations"]
            color = {"critical": "red", "high": "orange", "medium": "yellow", "low": "blue"}[severity]
            severity_stats += f"""
            <div class="stat-card {severity}">
                <h3>{severity.capitalize()}</h3>
                <span class="count">{count}</span>
            </div>"""
        
        # Top violations
        violations_html = ""
        for rule_id, violations in report["violations_by_rule"].items():
            if violations:
                rule_name = violations[0].rule_name
                violations_html += f"""
                <div class="violation-item">
                    <h4>{rule_name}</h4>
                    <span class="badge">{len(violations)} violations</span>
                    <p>{violations[0].recommendation}</p>
                </div>"""
        
        html_template = f"""
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CLAUDE.md Compliance Dashboard</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; text-align: center; }}
        .score {{ font-size: 3em; font-weight: bold; margin: 10px 0; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }}
        .stat-card {{ background: white; padding: 20px; border-radius: 10px; text-align: center; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .stat-card.critical {{ border-left: 5px solid #e74c3c; }}
        .stat-card.high {{ border-left: 5px solid #f39c12; }}
        .stat-card.medium {{ border-left: 5px solid #f1c40f; }}
        .stat-card.low {{ border-left: 5px solid #3498db; }}
        .count {{ font-size: 2em; font-weight: bold; color: #2c3e50; }}
        .violations {{ background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .violation-item {{ padding: 15px; border-bottom: 1px solid #eee; }}
        .violation-item:last-child {{ border-bottom: none; }}
        .badge {{ background: #e74c3c; color: white; padding: 5px 10px; border-radius: 20px; font-size: 0.8em; }}
        .recommendations {{ background: #ecf0f1; padding: 20px; border-radius: 10px; margin-top: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ CLAUDE.md Compliance Dashboard</h1>
            <div class="score">{summary['compliance_score']}%</div>
            <p>Toplam {summary['total_files_checked']} dosya kontrol edildi</p>
            <p>Son güncelleme: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <div class="stats">
            {severity_stats}
        </div>
        
        <div class="violations">
            <h2>🚨 Compliance Violations</h2>
            {violations_html if violations_html else "<p>🎉 Hiç violation bulunamadı!</p>"}
        </div>
        
        <div class="recommendations">
            <h3>💡 Öneriler</h3>
            <ul>
                {chr(10).join(f"<li>{rec}</li>" for rec in report.get('recommendations', []))}
            </ul>
        </div>
    </div>
</body>
</html>"""
        
        return html_template
    
    def create_pre_commit_config(self) -> str:
        """
        pre-commit framework için yapılandırma dosyası oluşturur
        
        Returns:
            Config dosya yolu
        """
        config_content = """
# CLAUDE.md Compliance Pre-commit Configuration
repos:
  - repo: local
    hooks:
      - id: claude-compliance-check
        name: CLAUDE.md Compliance Check
        entry: python tools/internal/compliance_integration_tool.py --staged
        language: system
        types: [python]
        stages: [commit]
        
      - id: claude-compliance-full
        name: CLAUDE.md Full Project Compliance
        entry: python tools/internal/compliance_integration_tool.py --full
        language: system
        types: [python]
        stages: [push]
"""
        
        config_path = os.path.join(self.project_root, ".pre-commit-config.yaml")
        with open(config_path, 'w') as f:
            f.write(config_content.strip())
        
        logger.info(f"Pre-commit config oluşturuldu: {config_path}")
        return config_path
    
    def install_compliance_system(self) -> bool:
        """
        Tüm compliance sistemini kurar
        
        Returns:
            Kurulum başarılı mı
        """
        try:
            logger.info("🔧 CLAUDE.md Compliance sistemi kuruluyor...")
            
            # Git hooks kur
            hooks_success = self.setup_git_hooks()
            
            # Pre-commit config oluştur
            config_path = self.create_pre_commit_config()
            
            # Dashboard oluştur
            dashboard_path = self.generate_compliance_dashboard()
            
            # İlk compliance check yap
            initial_report = self.compliance_checker.check_project_compliance()
            self.compliance_checker.print_summary_report(initial_report)
            
            # Status dosyası oluştur
            status = {
                "installation_date": datetime.now().isoformat(),
                "git_hooks_installed": hooks_success,
                "pre_commit_config": config_path,
                "dashboard_path": dashboard_path,
                "initial_compliance_score": initial_report["summary"]["compliance_score"]
            }
            
            status_path = os.path.join(self.compliance_dir, "installation_status.json")
            with open(status_path, 'w') as f:
                json.dump(status, f, indent=2)
            
            logger.info("✅ CLAUDE.md Compliance sistemi başarıyla kuruldu!")
            logger.info(f"📊 Dashboard: {dashboard_path}")
            logger.info(f"📋 Status: {status_path}")
            
            return True
            
        except Exception as e:
            logger.error(f"Compliance sistem kurulumu hatası: {e}")
            return False


def main():
    """
    Command line interface
    """
    import sys
    
    tool = ComplianceIntegrationTool()
    
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        
        if arg == "--install":
            tool.install_compliance_system()
        elif arg == "--staged":
            success = tool.check_staged_files_compliance()
            sys.exit(0 if success else 1)
        elif arg == "--full":
            success = tool.full_project_compliance_check()
            sys.exit(0 if success else 1)
        elif arg == "--dashboard":
            dashboard_path = tool.generate_compliance_dashboard()
            print(f"Dashboard: {dashboard_path}")
        else:
            print("Usage: python compliance_integration_tool.py [--install|--staged|--full|--dashboard]")
    else:
        # Default: install
        tool.install_compliance_system()


def auto_compliance_subagent():
    """Otomatik compliance check için subagent trigger"""
    try:
        from app.mcp_core import registry
        task_tool = registry.get_tool("task")
        
        if task_tool:
            # Subagent'i otomatik tetikle
            result = task_tool.execute_action(
                "create_task",
                description="Auto compliance check",
                prompt="CLAUDE.md compliance checker çalıştır ve kritik ihlalleri raporla",
                subagent_type="general-purpose"
            )
            return result.success
    except Exception as e:
        print(f"Auto subagent error: {e}")
        return False

if __name__ == "__main__":
    main()